# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        - Acme\AuthenticationBundle\Token\CustomAuthenticationToken

    totp:
        enabled: true
        issuer: 'Exclusive Immobilien'
        parameters:
            image: 'https://my-service/img/logo.png'
        template: 'security/2fa_form.html.twig'